### ISSUE TITLE
Bungee Inline stripe missing

### ISSUE THREAD

**Issue by nklansford** [nklansford/Design-System#3]
Used the import for bungee inline, but does not give me the stripe on the website.

**Comment by philschanely** [comment]
This is annoying, but some browsers render weights slightly differently. Because that inner stripe is so tiny its just hard to see at small sizes. If you blow the size up you'll begin to see it. You can attempt to help by setting `font-size: 400` or `font-size: regular` on elements that use that font but there's sadly only so much we can do. :(
